name: BLOG_PROJECT CI

on:
  push:
    paths:
      - 'blog_project/**'
  pull_request:
    paths:
      - 'blog_project/**'
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r blog_project/requirements.txt
    - name: Run Tests
      run: |
        python blog_project/blog/manage.py test articles

  cd:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: ci  # Only run CD if CI passes
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: printf "%s" "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Docker metadata
        id: meta
        run: |
          echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/blog_project" >> $GITHUB_ENV
          echo "TAG=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$TAG -f blog_project/Dockerfile .

      - name: Push Docker image to hub
        run: |
          docker push $IMAGE_NAME:$TAG
          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest


# push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
