name: Python CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

steps:
  - name: Checkout Code
    uses: 

  - name: setup Python
    uses: 
    with:
      python-version: 3.9


  - name: Install Dependencies
    run: |
     python -m install pip
     pip install django

  - name: run tests
    run:
      pytest
     
